In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/faults_mini.csv')
df.info()
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   X_Minimum              10 non-null     int64
 1   Y_Minimum              10 non-null     int64
 2   Pixels_Areas           10 non-null     int64
 3   Steel_Plate_Thickness  10 non-null     int64
 4   Pastry                 10 non-null     int64
 5   Z_Scratch              10 non-null     int64
 6   K_Scatch               10 non-null     int64
dtypes: int64(7)
memory usage: 688.0 bytes


X_Minimum  Y_Minimum  Pixels_Areas  ...  Pastry  Z_Scratch  K_Scatch
0         42     270900           267  ...       1          0         0
1       1084     185575           108  ...       0          0         1
2       1109    1170194           130  ...       0          1         0
3        190     210936           132  ...       1          0         0
4        330     429227           264  ...       1          0         0
5         74     779144          1506  ...       1          0         0
6         51     585861           139  ...       0          1         0
7        397     604478           444  ...       0          1         0
8         43     366881          4048  ...       0          0         1
9         48     377537          3985  ...       0          0         1

[10 rows x 7 columns]

In [5]:
input_cnt  = 4
output_cnt = 3
data = np.asarray(df, dtype='float32')
print(data)


[[4.200000e+01 2.709000e+05 2.670000e+02 8.000000e+01 1.000000e+00
  0.000000e+00 0.000000e+00]
 [1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02 0.000000e+00
  1.000000e+00 0.000000e+00]
 [1.900000e+02 2.109360e+05 1.320000e+02 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [3.300000e+02 4.292270e+05 2.640000e+02 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [7.400000e+01 7.791440e+05 1.506000e+03 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [5.100000e+01 5.858610e+05 1.390000e+02 7.000000e+01 0.000000e+00
  1.000000e+00 0.000000e+00]
 [3.970000e+02 6.044780e+05 4.440000e+02 7.000000e+01 0.000000e+00
  1.000000e+00 0.000000e+00]
 [4.300000e+01 3.668810e+05 4.048000e+03 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [4.800000e+01 3.775370e+05 3.985000e+03 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]]


In [6]:
RND_MEAN = 0
RND_STD  = 1
weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
bias   = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])

print("weight.shape : ", weight.shape)
print("bias.shape : ", bias.shape)
print("data.shape : ", data.shape)

mb_size     = 2
train_ratio = 0.8

MiniBatch_step_count = int(data.shape[0] * train_ratio) // mb_size
print("MiniBatch_step_count :", MiniBatch_step_count)

test_begin_index = MiniBatch_step_count * mb_size
print("test_begin_index : ",test_begin_index)

mb_size     = 10
train_ratio = 0.75
data_count  = 4123

MiniBatch_step_count = int(data_count * train_ratio) // mb_size
print("MiniBatch_step_count :", MiniBatch_step_count)

test_begin_index = MiniBatch_step_count * mb_size
print("test_begin_index : ",test_begin_index)

shuffle_map = np.arange(data.shape[0])
print(shuffle_map)
print("====================")
np.random.shuffle(shuffle_map)
print(shuffle_map)

mb_data_1 = data[shuffle_map[0:2]]
mb_data_2 = data[shuffle_map[2:4]]
mb_data_3 = data[shuffle_map[4:6]]
mb_data_4 = data[shuffle_map[6:8]]

print(mb_data_1)
print(mb_data_2)
print(mb_data_3)
print(mb_data_4)

weight.shape :  (4, 3)
bias.shape :  (3,)
data.shape :  (10, 7)
MiniBatch_step_count : 4
test_begin_index :  8
MiniBatch_step_count : 309
test_begin_index :  3090
[0 1 2 3 4 5 6 7 8 9]
[0 3 6 8 7 4 1 5 2 9]
[[4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01 1.00000e+00 0.00000e+00
  0.00000e+00]
 [1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]
 [4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]]
[[3.97000e+02 6.04478e+05 4.44000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[1.08400e+03 1.85575e+05 1.08000e+02 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]
 [7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]


In [7]:
print("====== 첫 번째 미니배치의 독립변수와 종속변수 ======")
mb_1_train_x = mb_data_1[:, :-3]
mb_1_train_y = mb_data_1[:, -3:]
print("mb_1_train_x : \n", mb_1_train_x)
print("mb_1_train_y : \n", mb_1_train_y)

print("====== 두 번째 미니배치의 독립변수와 종속변수 ======")
mb_2_train_x = mb_data_2[:, :-3]
mb_2_train_y = mb_data_2[:, -3:]
print("mb_2_train_x : \n", mb_2_train_x)
print("mb_2_train_y : \n", mb_2_train_y)

print("====== 세 번째 미니배치의 독립변수와 종속변수 ======")
mb_3_train_x = mb_data_3[:, :-3]
mb_3_train_y = mb_data_3[:, -3:]
print("mb_3_train_x : \n", mb_3_train_x)
print("mb_3_train_y : \n", mb_3_train_y)

print("====== 네 번째 미니배치의 독립변수와 종속변수 ======")
mb_4_train_x = mb_data_4[:, :-3]
mb_4_train_y = mb_data_4[:, -3:]
print("mb_4_train_x : \n", mb_4_train_x)
print("mb_4_train_y : \n", mb_4_train_y)

====== 첫 번째 미니배치의 독립변수와 종속변수 ======
mb_1_train_x : 
 [[4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01]
 [1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02]]
mb_1_train_y : 
 [[1. 0. 0.]
 [1. 0. 0.]]
====== 두 번째 미니배치의 독립변수와 종속변수 ======
mb_2_train_x : 
 [[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01]
 [4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01]]
mb_2_train_y : 
 [[0. 1. 0.]
 [0. 0. 1.]]
====== 세 번째 미니배치의 독립변수와 종속변수 ======
mb_3_train_x : 
 [[3.97000e+02 6.04478e+05 4.44000e+02 7.00000e+01]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02]]
mb_3_train_y : 
 [[0. 1. 0.]
 [1. 0. 0.]]
====== 네 번째 미니배치의 독립변수와 종속변수 ======
mb_4_train_x : 
 [[1.08400e+03 1.85575e+05 1.08000e+02 4.00000e+01]
 [7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02]]
mb_4_train_y : 
 [[0. 0. 1.]
 [1. 0. 0.]]


In [8]:
print("첫 번째 미니배치의 순전파 연산 결과")
mb_1_y_hat_1 = np.matmul(mb_1_train_x, weight[:, 0]) + bias[0]
mb_1_y_hat_2 = np.matmul(mb_1_train_x, weight[:, 1]) + bias[1]
mb_1_y_hat_3 = np.matmul(mb_1_train_x, weight[:, 2]) + bias[2]

print(mb_1_y_hat_1)
print(mb_1_y_hat_2)
print(mb_1_y_hat_3)


print("두 번째 미니배치의 순전파 연산 결과")

mb_2_y_hat_1 = np.matmul(mb_2_train_x, weight[:, 0]) + bias[0]
mb_2_y_hat_2 = np.matmul(mb_2_train_x, weight[:, 1]) + bias[1]
mb_2_y_hat_3 = np.matmul(mb_2_train_x, weight[:, 2]) + bias[2]

print(mb_2_y_hat_1)
print(mb_2_y_hat_2)
print(mb_2_y_hat_3)


print("세 번째 미니배치의 순전파 연산 결과")

mb_3_y_hat_1 = np.matmul(mb_3_train_x, weight[:, 0]) + bias[0]
mb_3_y_hat_2 = np.matmul(mb_3_train_x, weight[:, 1]) + bias[1]
mb_3_y_hat_3 = np.matmul(mb_3_train_x, weight[:, 2]) + bias[2]

print(mb_3_y_hat_1)
print(mb_3_y_hat_2)
print(mb_3_y_hat_3)

print("네 번째 미니배치의 순전파 연산 결과")

mb_4_y_hat_1 = np.matmul(mb_4_train_x, weight[:, 0]) + bias[0]
mb_4_y_hat_2 = np.matmul(mb_4_train_x, weight[:, 1]) + bias[1]
mb_4_y_hat_3 = np.matmul(mb_4_train_x, weight[:, 2]) + bias[2]

print(mb_4_y_hat_1)
print(mb_4_y_hat_2)
print(mb_4_y_hat_3)

첫 번째 미니배치의 순전파 연산 결과
[205618.48582159 160048.39482831]
[139559.06780318 108653.46081018]
[55212.02020052 42730.28705487]
두 번째 미니배치의 순전파 연산 결과
[444978.95431096 275845.25228852]
[301238.04350068 193333.97529765]
[119576.10066077  74721.36851946]
세 번째 미니배치의 순전파 연산 결과
[458572.09856934 325660.53630355]
[311233.34359913 221000.15514913]
[122999.98783054  87180.76660765]
네 번째 미니배치의 순전파 연산 결과
[139878.75021808 590871.28718174]
[ 95713.87261525 402215.73853847]
[ 36717.22122448 158906.11313164]


In [9]:
weight[:, 0]

array([-0.96851985,  0.75972448, -0.70668368,  0.48523394])

In [10]:
mb_total = np.vstack((mb_data_1,mb_data_2, mb_data_3, mb_data_4))

In [11]:
mb_total_x = mb_total[:, :-3]
mb_total_x.shape

(8, 4)

In [12]:
mb_total_y_hat = np.matmul(mb_total_x, weight) + bias 
print(mb_total_y_hat)

[[205618.48582159 139559.06780318  55212.02020052]
 [160048.39482831 108653.46081018  42730.28705487]
 [444978.95431096 301238.04350068 119576.10066077]
 [275845.25228852 193333.97529765  74721.36851946]
 [458572.09856934 311233.34359913 122999.98783054]
 [325660.53630355 221000.15514913  87180.76660765]
 [139878.75021808  95713.87261525  36717.22122448]
 [590871.28718174 402215.73853847 158906.11313164]]


In [13]:
print(mb_1_y_hat_1,mb_1_y_hat_2,mb_1_y_hat_3)
print(mb_2_y_hat_1,mb_2_y_hat_2,mb_2_y_hat_3)
print(mb_3_y_hat_1,mb_3_y_hat_2,mb_3_y_hat_3)
print(mb_4_y_hat_1,mb_4_y_hat_2,mb_4_y_hat_3)

[205618.48582159 160048.39482831] [139559.06780318 108653.46081018] [55212.02020052 42730.28705487]
[444978.95431096 275845.25228852] [301238.04350068 193333.97529765] [119576.10066077  74721.36851946]
[458572.09856934 325660.53630355] [311233.34359913 221000.15514913] [122999.98783054  87180.76660765]
[139878.75021808 590871.28718174] [ 95713.87261525 402215.73853847] [ 36717.22122448 158906.11313164]
