In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/faults.csv')

df_dataset = df[['X_Minimum','X_Maximum','Steel_Plate_Thickness','LogOfAreas',
                 'Pastry','Z_Scratch','Bumps']]
print("df_dataset.shape : ", df_dataset.shape)

df_dataset = np.asarray(df_dataset, dtype='float32')

df_dataset_x = df_dataset[0:1, : -3]
df_dataset_y = df_dataset[0:1, -3:]

print("df_dataset_x : ", df_dataset_x)
print("df_dataset_x.shape : ", df_dataset_x.shape)
print("df_dataset_y : ", df_dataset_y)
print("df_dataset_y.shape : ", df_dataset_y.shape)

df_dataset.shape :  (1941, 7)
df_dataset_x :  [[42.     50.     80.      2.4265]]
df_dataset_x.shape :  (1, 4)
df_dataset_y :  [[1. 0. 0.]]
df_dataset_y.shape :  (1, 3)


In [6]:
RND_MEAN = 0
RND_STD  = 1

input_cnt = df_dataset_x.shape[-1]
output_cnt = df_dataset_y.shape[-1]

weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt,output_cnt])
bias   = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])

print("weight.shape : ", weight.shape)
print("bias.shape : ", bias.shape)

print("==================================================")

print("df_dataset_x : \n", df_dataset_x)
print("weight : \n", weight)
print("bias : \n", bias)

print("==================================================")

P_1 = np.matmul(df_dataset_x[0],weight[:,0]) + bias[0]
P_2 = np.matmul(df_dataset_x[0],weight[:,1]) + bias[1]
P_3 = np.matmul(df_dataset_x[0],weight[:,2]) + bias[2]

P_total = np.matmul(df_dataset_x, weight) + bias

print(P_1)
print(P_2)
print(P_3)
print(P_total)

print("===================================================")

print("df_dataset_x :", df_dataset_x)
print("df_dataset_x[0] : ", df_dataset_x[0])



weight.shape :  (4, 3)
bias.shape :  (3,)
df_dataset_x : 
 [[42.     50.     80.      2.4265]]
weight : 
 [[ 1.89748904e+00 -2.77630180e+00 -1.10008768e+00]
 [ 2.55624712e-04 -1.24653037e+00 -6.72048655e-01]
 [ 6.30188463e-01  8.25970735e-02 -7.43611510e-01]
 [ 1.47822455e+00 -1.16866598e+00 -6.62934177e-01]]
bias : 
 [0.77055073 0.61706945 0.42250923]
134.47986085022023
-174.54212655018372
-140.48113689463594
[[ 134.47986085 -174.54212655 -140.48113689]]
df_dataset_x : [[42.     50.     80.      2.4265]]
df_dataset_x[0] :  [42.     50.     80.      2.4265]
